id = "cli"
url = ""
hidden = true

[match]
regex_wmclass = "^$"
regex_title = "^$"

[section]

[section."Shell History"]
"Ctrl + r" = "Reverse cmd search / find next"
"`history | grep <term>`" = "Search for \"<term>\""
"`history 10`" = "Print last 10 cmds"
"!3" = "Execute cmd 3 from history"

[section."Data Wrangling"]
"`awk '{print $1}'`" = "Column base manipulations"
"`sed -E 's/.*(d+)/\\1/'`" = "Line base manipulations"
"`paste -sd,`" = "Concatenate lines"
"`tail -n10`" = "Last lines"
"`head -n10`" = "First lines"
"`uniq -c`" = "Count unique lines"
"`sort -nk1,1" = "Sort by column 1"

[section.Tools]
bc = "Calculator"
"gtop / htop" = "System Monitors"
xplr = "File manager"
moc = "Music Player in Console"
nvtop = "NVidia Card usage"
fd = "Easy to use find clone"
hyperfine = "Benchmarking"
tl = "TooLong log file viewer"
bat = "cat clone to view files with style"
eza = "ls clone with coloring"
duf = "Basic disk usage"
ncdu = "Recursive disk usage analyzer"
s-tui = "Stress test and monitor"
btm = "System resources dashboard"

[section.Navigating]
pwd = "Print working dir"
cd = "Change to home dir"
"`cd -`" = "Change to previous dir"

[section.Debugging]
"journalctl --since \"1m ago\"" = "System logs since time"
"journalctl -k" = "System logs since boot"
