style:
  alpha: 1
  font_family:
  font_base_size: 14
  max_rows: 20
  show_statusbar: true

  background_color: "#1F232B"
  title_color: "#eceff4"
  group_title_color: "#5e81ac"
  description_color: "#eceff4"
  keys_color: "#e5e9f0"
  statusbar_color: "#4c566a"

behavior:
  close_on_mouse_out: true
  close_on_esc: true
  close_on_anykey: true
