id = "firefox-tridactyl"
url = "https://github.com/tridactyl/tridactyl"
hidden = true

[match]
regex_wmclass = "$^"
regex_title = "$^"

[section]
[section.Modes]
Esc = "Normal"
f = "Hint"
v = "Visual"
":" = "Command"
"Shift + Esc" = "Ignore"

[section.Tabs]
"J / K" = "Next / previous"
"d / x" = "Close"
"u / X" = "Reopen"
t = "Create new"
b = "Switch between"
"gt / GT" = "Go to next / previous"
yt = "Duplicate"
W = "Move tab new window"

[section.Normal]
"H / L" = "History back / forward"
"o / O" = "Open URL in current tab"
"t / T" = "Open URL in new tab"
"w / W" = "Open URL in new Window"
"p / P" = "Open clipboard in current/new tab"
"s / S" = "Search with engine / in new tab"
"gg / G" = "Scroll to start / end"
yy = "Copy URL to clipboard"
"zi / zo / zz" = "Zoom in / out / reset"
"\\/" = "Search"

[section.Hint]
f = "Open in current tab"
F = "Open in new background tab"
"; + h" = "Select element"
"; + y" = "Copy link to clipboard"
"; + p" = "Copy element to clipboard"
"; + k" = "Kill element"

[section.Visual]
hjklewb = "Adjust selection"
y = "yank to clipboard"
"s / S" = "Search selected text in current /new tab"
f = "Open link in current tab"
F = "Open link new current tab"
H = "Back in History"
L = "Forward in History"
