id: tilix
title: Tilix
source: 
match:
  regex_process: Tilix
  regex_title: .*
  
hints:
  Window:
    F11: Toggle fullscreen
    F12: View session sidebar
  
  Sessions:
    Ctrl + Shift + T: Open new session
    Ctrl + PageUp / PageDown: Switch to next/preview session
    Ctrl + Shift + Q: Close current session

  Tiling:
    Ctrl + Alt + A: Add terminal automatically
    Ctrl + Alt + R: Add terminal right
    Ctrl + Alt + D: Add terminal down
    Shift + Alt + Up Down Left Right: Resize terminal

  Terminal:
    Shift + Ctrl + F: Find
    Shift + Ctrl + G / H: Find next / previous
    Shift + Ctrl + Up Down: Scroll up / down
    Shift + PageUp PageDown: Page up / down
    Shift + Ctrl + W: Close

  Navigate cmds:
    pwd: Print working dir
    cd: Change to home dir
    "`cd -`": Change to previous dir

  History cmds:
    "`history | grep <term>`": Search for "<term>"
    "`history 10`": Print last 10 cmds
    "!3": Execute cmd 3 from history
    Ctrl + r: Reverse cmd search / find next

  Tools cmds:
    bc: Calculator
    gtop / htop: System Monitors
    ranger: File manager
    moc: Music Player in Console
    alsamixer: Audio Mixer    
